# Generated by Django 4.2.11 on 2024-04-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pizza_date_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
