# Generated by Django 4.2.11 on 2024-04-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_pizza_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
