# Generated by Django 4.2.11 on 2024-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_pizza_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Укажите цену BYN', max_digits=5),
        ),
    ]
