# Generated by Django 4.2.11 on 2024-05-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_pizza_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='text',
            field=models.TextField(blank=True, help_text='Дайте описание пиццы', max_length=1000, null=True),
        ),
    ]
