# Generated by Django 4.2.11 on 2024-05-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_cart_cartitem_cart_items_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование вакансии', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите зарплату в BYN', max_digits=5)),
                ('text', models.TextField(blank=True, help_text='Описание вакансии', max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pizza',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
