# Generated by Django 4.2.11 on 2024-05-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_jobs_remove_cartitem_cart_remove_cartitem_pizza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Укажите зарплату в BYN', max_digits=5, null=True),
        ),
    ]
